CREATE TABLE publish(
  id SERIAL PRIMARY KEY,
  app_name VARCHAR NOT NULL,
  file_name VARCHAR,
  gateway_url VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
